version: '3.8'

services:
  seq: 
    image: datalust/seq:2023.1
    container_name: seq
    ports:
      - "5340:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_LICENSE=trial
    volumes:
      - ./seq:/data
